### PR TITLE
added meta-data-query section

### PR DESCRIPTION
**Pull request by jh87692**
### What does this PR do?

Added the simple query page which interacts with the API server.
The results are a placeholder at the moment as the File component isn't suitable for rendering elements returned.

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you successfully ran tests with your changes locally? Including container validation.
* [x] Have you lint your code locally prior to submission?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x] Have you labelled this PR correctly? E.G. major, milestone, breaking, breaking-change, minor, feature, enhancement, patch, fix, chore, refactor etc

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your core changes, as applicable?

### CODE REVIEW

**Comment by Nepomuceno** [comment]
Should we change the file names to kebab-case?

**Comment by jh87692** [comment]
> Should we change the file names to kebab-case?

I shall do that now sir!

**Comment by 777arc** [comment]
good point that the File/Directory components arent set up to render elements returned, but if you look at the metadata_collection.data structure (see below), I think we can have the results of the query essentially replace that structure
image

**Comment by jh87692** [comment]
> good point that the File/Directory components arent set up to render elements returned, but if you look at the metadata_collection.data structure (see below), I think we can have the results of the query essentially replace that structure image

how would we like the results displaying?

**Comment by 777arc** [comment]
We can do it as a separate PR imo

**Pull request closed without merging**
