### PR TITLE
Added download button when viewing a recording

### PR DESCRIPTION
**Pull request by javAlborz**

### CODE REVIEW

**Comment by 777arc** [comment]
You could try using the existing downlink links that are on the browser page, eg https://github.com/IQEngine/IQEngine/blob/main/client/src/pages/browser/file-row.tsx#L131

most of the meat is here https://github.com/IQEngine/IQEngine/blob/main/client/src/utils/sigmfMetadata.ts#L107

although I see you're also trying to zip it before the download, which might not be worth the complexity because zipping binary IQ files usually doesnt lead to much savings in disk space.

**Comment by 777arc** [comment]
btw feel free to ping me on discord if you want help with any of this, eg testing it or whatnot

**Comment by 777arc** [comment]
oh actually I think this is one of those bots that tries to solve github issues with ML, clearly failing in this case

**Comment by javAlborz** [comment]
Hi Marc. This is my first github issue, but would be happy yo try to help

-Alborz

**Comment by javAlborz** [comment]
Hi Marc. Sent you a message on Discord would be happy yo try to help out

**Comment by 777arc** [comment]
> Hi Marc. Sent you a message on Discord would be happy yo try to help out

Not seeing anything on Discord

**Pull request closed without merging**
