### PR TITLE
time cursor, toggle entire sample

### PR DESCRIPTION
**Pull request by jh87692**
### What does this PR do?
allows the selection of the entire sample (via time cursor bounds) to push entirety to plugin server

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you successfully ran tests with your changes locally? Including container validation.
* [x] Have you lint your code locally prior to submission?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x] Have you labelled this PR correctly? E.G. major, milestone, breaking, breaking-change, minor, feature, enhancement, patch, fix, chore, refactor etc

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your core changes, as applicable?

### CODE REVIEW

**Comment by Nepomuceno** [comment]
That would not work now because the cursor would try to download the whole file to the browser immediately

**Comment by Nepomuceno** [comment]
That would not work now because the cursor would try to download the whole file to the browser immediately

**Comment by 777arc** [comment]
Yeah I think a new checkbox in the plugin section called "entire recording" and disabled by default would be nice.  I was also meaning to make it so when you don't have the time cursors enabled, it just uses whatever span is visible on your screen, up to you if you want to also add that.

**Comment by jh87692** [comment]
> Yeah I think a new checkbox in the plugin section called "entire recording" and disabled by default would be nice. I was also meaning to make it so when you don't have the time cursors enabled, it just uses whatever span is visible on your screen, up to you if you want to also add that.

yeah that makes sense. I'll modify it tomorrow

**Pull request closed without merging**
