### PR TITLE
Avoid unecessary refresh of metadata

### PR DESCRIPTION
**Pull request by Nepomuceno**
### What does this PR do?

This make the stale time of the metadata queries to be infinity so they are always fresh this has the side effect that once you open a metadarta file you will not get updates made by others in that metadata file while in your session.

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you successfully ran tests with your changes locally? Including container validation.
* [x] Have you lint your code locally prior to submission?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x] Have you labelled this PR correctly? E.G. major, milestone, breaking, breaking-change, minor, feature, enhancement, patch, fix, chore, refactor etc

### CODE REVIEW

**Review by 777arc — APPROVED** [review]

**Comment by Jaydee123** [comment]
> ### What does this PR do?
> This make the stale time of the metadata queries to be infinity so they are always fresh this has the side effect that once you open a metadarta file you will not get updates made by others in that metadata file while in your session.
> 
> ### All Submissions:
> * [x]  Have you followed the guidelines in our Contributing document?
> * [x]  Have you successfully ran tests with your changes locally? Including container validation.
> * [x]  Have you lint your code locally prior to submission?
> * [x]  Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
> * [x]  Have you labelled this PR correctly? E.G. major, milestone, breaking, breaking-change, minor, feature, enhancement, patch, fix, chore, refactor etc

will it still fetch latest when you move between pages?

**Comment by sebastus** [comment]
can we hold off on merging - found another bug - testing to see if this PR fixes it.

**Comment by Nepomuceno** [comment]
> 
> will it still fetch latest when you move between pages?

Only if we manually invalidate the cache of the metadata once it is in cache will be in cache for until the garbage collector takes it. important to notice though that the version that ill be in cache it si the verrsion that was returned from the api. so if you open the spectrogram again it will be showing the version that is from the api not the version that you were working previously but did not save.

**Comment by sebastus** [comment]
The bugs I found seem to be fixed.

**Review by sebastus — APPROVED** [review]
lgtm

**Pull request merged**
